Preparació de dades

In [11]:
from sklearn import datasets

import numpy as np

iris = datasets.load_iris()

X = iris.data[:,[2,3]]
y = iris.target
print('Class labels:',np.unique(y))


Class labels: [0 1 2]


Separem conjunts entrenament 70% i test 30%

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 1, stratify = y)

#Estandarització
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
import pickle

with open('../models/sc.pck', 'wb') as f:
    pickle.dump(sc, f) 


Entrenament regresio

In [13]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=100.0,
                        random_state = 1,
                        solver = 'lbfgs',
                        multi_class='ovr')
lr.fit(X_train_std, y_train)

LogisticRegression(C=100.0, multi_class='ovr', random_state=1)

Serialitzem el model

In [14]:
import pickle

with open('../models/m_logistic.pck', 'wb') as f:
    pickle.dump(lr, f)  


entrenament SVM i serialitzem

In [15]:
from sklearn.svm import SVC
import pickle

svm = SVC(kernel='linear',C=1.0, random_state=1)
svm.fit(X_train_std, y_train)

 

SVC(kernel='linear', random_state=1)

In [16]:
with open('../models/m_svm.pck', 'wb') as f:
    pickle.dump(svm, f)  

predictions = svm.predict(X_test_std)
predictions   

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])

Trees

In [17]:
from sklearn.tree import DecisionTreeClassifier
import pickle

tree_model = DecisionTreeClassifier(criterion='gini',max_depth=2, random_state=1)
tree_model.fit(X_train,y_train)

with open('../models/m_tree.pck', 'wb') as f:
    pickle.dump(tree_model, f) 

predictions = tree_model.predict(X_test_std)
predictions         

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0])

KNN

In [18]:
from sklearn.neighbors import KNeighborsClassifier
import pickle

knn = KNeighborsClassifier(n_neighbors=3, p=2, metric='minkowski')
knn.fit(X_train_std, y_train)

print(type(knn))

with open('../models/m_knn.pck', 'wb') as f:
    pickle.dump(knn, f)

predictions = knn.predict(X_test_std)
predictions        

<class 'sklearn.neighbors._classification.KNeighborsClassifier'>


array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])